import { test, expect } from '@playwright/test'
const origin = 'http://127.0.0.1:5173'

test('test entry requires all details, persists employee ID and displays profile', async ({ page }) => {
  await page.clock.install()
  await page.goto(`${origin}/tas/course`)
  await expect(page.locator('.participant-entry')).toHaveCount(0)
  await page.goto(`${origin}/tas/exercise/section-1`)
  const form = page.locator('.participant-entry form')
  await expect(form).toBeVisible()
  await expect(page.locator('.exercise-question')).toHaveCount(0)
  await form.getByRole('button').click()
  await expect(form).toBeVisible()
  await form.getByLabel('Nama', { exact: true }).fill('   ')
  await form.getByLabel('Jabatan').fill('Quantity Surveyor')
  await form.getByLabel('No. Karyawan').fill('001-A')
  await form.getByRole('button').click()
  await expect(form).toBeVisible()
  await form.getByLabel('Nama', { exact: true }).fill('Ayu Putri')
  for (const id of ['001-A', '12345']) {
    await form.getByLabel('No. Karyawan').fill(id)
    await form.getByRole('button').click()
    await expect(form).toBeVisible()
  }
  await form.getByLabel('No. Karyawan').fill('000012')
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/participant-entry-mobile.png', fullPage: true })
  await form.getByRole('button').click()
  await expect(page.locator('.participant-entry')).toHaveCount(0)
  await expect(page.locator('.participant-profile-card dd')).toHaveText(['Ayu Putri', 'Quantity Surveyor', '000012'])
  await expect(page.getByRole('button', { name: 'Ubah data diri' })).toBeDisabled()
  await page.reload()
  await expect(page.locator('.participant-entry')).toHaveCount(0)
  await page.goto(`${origin}/trb/exercise/section-2`)
  await expect(page.locator('.participant-entry')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Ubah data diri' })).toBeDisabled()
  await page.clock.pauseAt(new Date(Date.now() + 60 * 1000))
  const remaining = await page.evaluate(() => JSON.parse(localStorage.getItem('cubicost:participant')).updatedAt + 60 * 60 * 1000 - Date.now())
  await page.clock.fastForward(remaining - 1)
  await expect(page.getByRole('button', { name: 'Ubah data diri' })).toBeDisabled()
  await page.clock.fastForward(1001)
  await expect(page.getByRole('button', { name: 'Ubah data diri' })).toBeEnabled()
  await page.getByRole('button', { name: 'Ubah data diri' }).click()
  await form.getByLabel('Jabatan').fill('Engineer')
  await form.getByRole('button').click()
  await page.goto(`${origin}/tas/tests?scores=tas`)
  await expect(page.locator('.course-scores').first().locator('dd')).toHaveText(['Ayu Putri', 'Engineer', '000012'])
  await expect(page.getByRole('button', { name: 'Ubah data diri' })).toBeDisabled()
  await page.reload()
  await expect(page.getByRole('button', { name: 'Ubah data diri' })).toBeDisabled()
  await page.clock.fastForward(60 * 60 * 1000)
  await expect(page.getByRole('button', { name: 'Ubah data diri' })).toBeEnabled()
})

test('legacy name pre-fills form and English labels work', async ({ page }) => {
  await page.goto(origin)
  await page.evaluate(() => localStorage.setItem('cubicost:student-name', 'Budi'))
  await page.goto(`${origin}/tas/exercise/section-3`)
  await page.locator('button[lang="en"]').click()
  const form = page.locator('.participant-entry form')
  await expect(form.getByLabel('Name', { exact: true })).toHaveValue('Budi')
  await expect(form.getByLabel('Job title')).toBeVisible()
  await expect(form.getByLabel('Employee ID')).toBeVisible()
  await page.screenshot({ path: 'test-results/participant-entry-desktop.png', fullPage: true })
})
