import { test, expect } from '@playwright/test'
const origin = 'http://127.0.0.1:5173'
const profile = { name: 'Ayu Putri', jobTitle: 'Quantity Surveyor', employeeId: '001-A' }
test.beforeEach(async ({ page }) => {
  await page.addInitScript(profile => {
    if (!localStorage.getItem('cubicost:participant')) localStorage.setItem('cubicost:participant', JSON.stringify(profile))
  }, profile)
})

test('hub separates learning and tests; score cards live on test pages', async ({ page }) => {
  await page.goto(origin)
  await expect(page.locator('.course-scores')).toHaveCount(0)
  await expect(page.locator('.hub-test-link')).toHaveCount(0)
  await page.locator('.lesson-topbar__tools a[href="/exercises"]').click()
  await expect(page).toHaveURL(`${origin}/exercises`)
  await expect(page.locator('.exercise-hub__card')).toHaveCount(3)
  await expect(page.locator('.course-scores')).toHaveCount(3)
  await page.screenshot({ path: 'test-results/exercise-hub-desktop.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/exercise-hub-mobile.png', fullPage: true })
  await page.setViewportSize({ width: 1280, height: 900 })
  await page.locator('.exercise-hub__card a').first().click()
  await expect(page).toHaveURL(`${origin}/tas/tests`)
  await expect(page.locator('.test-list > article')).toHaveCount(3)
  await expect(page.locator('.course-scores__content')).toBeVisible()
  await expect(page.locator('.course-scores dd')).toHaveText(Object.values(profile))
  await expect(page.locator('.course-scores__row strong')).toHaveText(['0/100', '0/100', '0/100'])
  await expect(page.getByRole('button', { name: 'Unduh kartu nilai' })).toBeDisabled()
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/test-page-mobile.png', fullPage: true })
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.screenshot({ path: 'test-results/test-page-desktop.png', fullPage: true })
  await page.goto(`${origin}/tme/tests`)
  await expect(page.getByText('Tes untuk kursus ini belum tersedia.')).toBeVisible()
})

test('legacy link, submission, result overview, PNG and retry preserve results', async ({ page }) => {
  await page.goto(`${origin}/tas/exercise/section-3`)
  await expect(page).toHaveURL(`${origin}/tas/tests/section-3`)
  await page.locator('button[lang="en"]').click()
  await page.getByRole('button', { name: 'Start test' }).click()
  for (const [index, answer] of [0, 1, 2, 0, 1].entries()) {
    await page.locator(`input[name="q${index + 1}"][value="${answer}"]`).check()
    await page.getByRole('button', { name: index === 4 ? 'Submit answers' : 'Next question' }).click()
  }
  await page.getByRole('link', { name: 'View test scores' }).click()
  await expect(page).toHaveURL(`${origin}/tas/tests?scores=tas`)
  await expect(page.locator('.course-scores__row strong')).toHaveText(['0/100', '0/100', '100/100'])
  const downloadEvent = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download score card' }).click()
  const download = await downloadEvent
  expect(download.suggestedFilename()).toBe('cubicost-tas-Ayu-Putri.png')
  await download.saveAs('test-results/downloaded-score-en.png')
  expect(await download.failure()).toBeNull()
  await page.getByRole('button', { name: 'Retry test' }).click()
  await expect(page.getByText('Question 1 / 5', { exact: true })).toBeVisible()
  await expect(page.locator('input:checked')).toHaveCount(0)
  await page.goto(`${origin}/tas/tests`)
  await expect(page.getByRole('link', { name: 'Continue test' })).toBeVisible()
  await expect(page.locator('.course-scores__content')).toBeVisible()
  await expect(page.locator('.course-scores__row strong')).toHaveText(['0/100', '0/100', '100/100'])
  await page.reload()
  await expect(page.locator('.course-scores__row strong')).toHaveText(['0/100', '0/100', '100/100'])
})

test('test page edits profile and loads existing results without changing learning progress', async ({ page }) => {
  await page.goto(`${origin}/trb/tests`)
  await page.evaluate(() => localStorage.setItem('cubicost:trb:section-1-exercise:v1', JSON.stringify({ started: true, submitted: true, index: 4, answers: { q1: '0', q2: '1', q3: '0', q4: '0', q5: '1' } })))
  await page.reload()
  await page.getByRole('button', { name: 'Ubah data diri' }).click()
  await page.getByLabel('Nama', { exact: true }).fill('Budi')
  await page.getByRole('button', { name: 'Lanjut ke tes' }).click()
  await expect(page.locator('.course-scores__content')).toBeVisible()
  await expect(page.locator('.course-scores dd').first()).toHaveText('Budi')
  await expect(page.locator('.course-scores__review')).toHaveText('Belum lulus')
  await expect(page.locator('.course-scores__pending')).toHaveCount(2)
  await expect(page.locator('.lesson-topbar input')).toHaveCount(0)
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('cubicost:tutorial:trb:progress')).completed)).toEqual([])
})
