import { test, expect } from '@playwright/test'

const origin = 'http://127.0.0.1:5173'
test('scores appear after submission and survive retry and reload', async ({ page }) => {
  await page.goto(`${origin}/tas/exercise/section-3`)
  await page.locator('button[lang="en"]').click()
  await expect(page.getByRole('link', { name: 'Score', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Start exercise' }).click()
  for (const [index, answer] of [0, 1, 2, 0, 1].entries()) {
    await page.locator(`input[name="q${index + 1}"][value="${answer}"]`).check()
    await page.getByRole('button', { name: index === 4 ? 'Submit answers' : 'Next question' }).click()
  }
  await page.getByRole('link', { name: 'View test scores' }).click()
  await expect(page.locator('.course-scores')).toHaveCount(3)
  await expect(page.locator('.course-scores').first()).toHaveAttribute('open', '')
  await expect(page.locator('.course-scores').first().locator('.course-scores__row strong').nth(2)).toHaveText('100/100')
  await page.locator('.course-scores').first().locator('.course-scores__row a').nth(2).click()
  await page.getByRole('button', { name: 'Try again' }).click()
  await page.reload()
  await page.goto(`${origin}/`)
  await page.locator('.course-scores summary').first().click()
  await expect(page.locator('.course-scores').first().locator('.course-scores__row strong').nth(2)).toHaveText('100/100')
  await page.setViewportSize({ width: 390, height: 844 })
  await page.locator('.course-scores summary').first().click()
  await expect(page.locator('.course-scores').first().locator('.course-scores__row strong').nth(2)).not.toBeVisible()
  await page.locator('.course-scores summary').first().focus()
  await page.keyboard.press('Enter')
  await expect(page.locator('.course-scores').first().locator('.course-scores__row strong').nth(2)).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('empty and existing saved submissions are supported', async ({ page }) => {
  await page.goto(`${origin}/`)
  await page.locator('button[lang="en"]').click()
  await expect(page.locator('.course-scores')).toHaveCount(3)
  await page.locator('.course-scores summary').first().click()
  await expect(page.locator('.course-scores').first().locator('.course-scores__row strong')).toHaveText(['0/100', '0/100', '0/100'])
  await expect(page.locator('.course-scores').first().locator('.course-scores__pending')).toHaveText(['Test not done yet', 'Test not done yet', 'Test not done yet'])
  await page.locator('.course-scores summary').nth(2).click()
  await expect(page.getByText('Tests are not available for this course yet.')).toBeVisible()
  await page.evaluate(() => localStorage.setItem('cubicost:trb:section-1-exercise:v1', JSON.stringify({ started: true, submitted: true, index: 4, answers: { q1: '0', q2: '1', q3: '0', q4: '0', q5: '1' } })))
  await page.reload()
  await expect(page.locator('.course-scores')).toHaveCount(3)
  await expect(page.locator('.hub-course-group').nth(1).locator('.course-scores')).toHaveCount(1)
  await page.locator('.course-scores summary').nth(1).click()
  await expect(page.locator('.course-scores').nth(1).locator('.course-scores__row strong')).toHaveText(['0/100', '0/100', '0/100'])
  await expect(page.locator('.course-scores').nth(1).locator('.course-scores__review')).toHaveText('Not passed')
  await expect(page.locator('.course-scores').nth(1).locator('.course-scores__pending')).toHaveCount(2)
  await page.locator('button[lang="id"]').click()
  await expect(page.locator('.course-scores summary')).toHaveText(['Nilai', 'Nilai', 'Nilai'])
})


test('opening scores keeps desktop course cards and buttons aligned', async ({ page }) => {
  await page.setViewportSize({ width: 1600, height: 1000 })
  await page.goto(`${origin}/`)
  const positions = () => page.locator('.hub-course-card__actions').evaluateAll(nodes => nodes.map(node => Math.round(node.getBoundingClientRect().top + window.scrollY)))
  const before = await positions()
  expect(new Set(before).size).toBe(1)
  await page.locator('.course-scores summary').first().click()
  expect(await positions()).toEqual(before)
  await expect(page.locator('.hub-course-card .course-scores')).toHaveCount(0)
  await page.screenshot({ path: 'test-results/score-cards-desktop.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  const course = await page.locator('.hub-course-card').first().boundingBox()
  const score = await page.locator('.course-scores').first().boundingBox()
  const nextCourse = await page.locator('.hub-course-card').nth(1).boundingBox()
  expect(score.y).toBeGreaterThan(course.y + course.height)
  expect(nextCourse.y).toBeGreaterThan(score.y + score.height)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/score-cards-mobile.png', fullPage: true })
})

test('profile name changes through the entry form and stays on score cards', async ({ page }) => {
  await page.goto(`${origin}/tas/exercise/section-1`)
  await page.locator('button[lang="en"]').click()
  await expect(page.locator('.lesson-topbar input')).toHaveCount(0)
  await page.getByRole('button', { name: 'Edit details' }).click()
  await page.getByLabel('Name', { exact: true }).fill('Ayu Putri')
  await page.getByRole('button', { name: 'Continue to test' }).click()
  await page.goto(`${origin}/?scores=tas`)
  await expect(page.locator('.course-scores .participant-details > div:first-child dd')).toHaveText(['Ayu Putri', 'Ayu Putri', 'Ayu Putri'])
  await expect(page.getByText('Section test scores', { exact: true })).toHaveCount(0)
  await page.reload()
  await expect(page.locator('.course-scores').first().locator('dd').first()).toHaveText('Ayu Putri')
})

test.beforeEach(async ({ page }) => {
  await page.addInitScript(() => {
    if (!localStorage.getItem('cubicost:participant')) localStorage.setItem('cubicost:participant', JSON.stringify({ name: 'Test User', jobTitle: 'Engineer', employeeId: '0012' }))
  })
})

test('score card downloads a PNG after a completed test', async ({ page }) => {
  await page.goto(`${origin}/?scores=tas`)
  const card = page.locator('.course-scores').first()
  await expect(card.getByRole('button', { name: 'Unduh kartu nilai' })).toBeDisabled()
  await page.evaluate(() => {
    localStorage.setItem('cubicost:tas:section-3-exercise:v1', JSON.stringify({ started: true, submitted: true, index: 4, answers: { q1: '0', q2: '1', q3: '2', q4: '0', q5: '1' } }))
    localStorage.setItem('cubicost:participant', JSON.stringify({ name: 'Ayu Putri', jobTitle: 'Quantity Surveyor', employeeId: '001-A' }))
  })
  await page.reload()
  await expect(card.getByRole('button', { name: 'Unduh kartu nilai' })).toBeEnabled()
  await expect(card).not.toContainText('Hanya tersimpan di browser ini.')
  const downloadEvent = page.waitForEvent('download')
  await card.getByRole('button', { name: 'Unduh kartu nilai' }).click()
  const download = await downloadEvent
  expect(download.suggestedFilename()).toBe('cubicost-tas-Ayu-Putri.png')
  await download.saveAs('test-results/downloaded-score-id.png')
  expect(await download.failure()).toBeNull()
  await page.locator('button[lang="en"]').click()
  const englishEvent = page.waitForEvent('download')
  await card.getByRole('button', { name: 'Download score card' }).click()
  await (await englishEvent).saveAs('test-results/downloaded-score-en.png')
})
